### PR TITLE
Better test

### PR DESCRIPTION
**Pull request by vesparny**
following up https://gist.github.com/MicheleBertoli/1fa247d96a6c8a3c86a2

@MicheleBertoli guess this one is a better approach.
I mocked the `Home` component in order to test `Counter` in isolation.
Thoughts?

### CODE REVIEW

**Comment by vesparny** [comment]
I'd also love to hear @gaearon 's take on the testing strategy path I took here

**Comment by MicheleBertoli** [comment]
@vesparny in my point of view, the two components are still too coupled.

I would suggest:

- the [container-component](https://medium.com/@learnreact/container-components-c0e67432e005) approach
- to move the `increment` method into the `Counter`. Then, if you need to do something in the parent component (e.g. an action) you can pass down a callback.
- test it using a mock/spy function

**Comment by vesparny** [comment]
@MicheleBertoli uhm...probably the problem is just about naming things?
I see the `Counter` receiving a callback as a prop named `handleClick`.
This is just calling `increment` on parent Component.

If I defined `increment ` in `Counter` I should call `setState()` there.
Am I wrong?

**Comment by MicheleBertoli** [comment]
Here is how to use [Spies](https://github.com/mochajs/mocha/wiki/Spies)

```javascript
const spy = sinon.spy();
const counter = TestUtils.renderIntoDocument(<Counter handleClick={spy} count={0} />);
const button = TestUtils.findRenderedDOMComponentWithTag(counter, 'a');
TestUtils.Simulate.click(button);
sinon.assert.calledOnce(spy);
```

**Comment by MicheleBertoli** [comment]
@vesparny I don't see it as a callback since the function changes the value of the `Counter`'s `count` property :)

**Comment by vesparny** [comment]
you mean something like?

```js
export default class Counter extends Component{

  static propTypes = {
    count: PropTypes.number.isRequired,
    handleClick: PropTypes.func.isRequired
  };

  increment() {
    return this.props.handleClick();
  }

  render() {
    const { count, handleClick } = this.props;

    return (
      <div className="Counter">
        <h1 className="h1 h0-responsive caps mt4 mb0 regular">Count: {count}</h1>
        <p className="h3">Click the button to increment the counter</p>
        <a
          onClick={this.increment}
          className="h3 button button-big mb4"
        >
          Increment
        </a>
      </div>
    );
  }
}
```

**Comment by MicheleBertoli** [comment]
Something like this (inside the `Counter` or the `Counter` container):

```javascript
  increment() {
    this.setState({
      counter: this.state.counter += 1
    }, this.props.onIncrement);
  }
```

**Comment by vesparny** [comment]
The component container in my case is `Home`.
I'd rather prefer not to call `setState()` inside the `Counter` Component.

Basically `Home` is my smart component, `Counter` is a dumb one.
Guess the approach is very similar compared to the one you suggested.
https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0

**Comment by MicheleBertoli** [comment]
ok, so maybe the names are misleading :)

**Comment by vesparny** [comment]
:)

**Comment by vesparny** [comment]
Anyways, the spy thing is interesting.
The only problem is that I need to instantiate my container/smart `Home` in order to verify that, after calling the click handler.

**Comment by vesparny** [comment]
@MicheleBertoli just renamed a bit things, and plugged a `spy` example.
It's very nice.

thanks for the hints.

Does it make more sense now for you?

**Comment by MicheleBertoli** [comment]
:+1:

**Comment by vesparny** [comment]
great, let squash and merge this

**Comment by MicheleBertoli** [comment]
Amazing!

**Comment by vesparny** [comment]
@MicheleBertoli it's been a nice exercise :)
And perhaps it could be useful to someone else.

**Pull request merged**
